services:
  backend:
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile.remote
    container_name: sso-demo_backend
    ports:
      - "8012:8080"
    tty: true
    env_file:
      - "./backend/.env"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /go/src/backend
        - action: rebuild
          path: ./backend

  redis:
    image: redis:latest
    container_name: sso-demo_redis
    ports:
      - "16379:6379"
    tty: true
    volumes:
      - ./redis/data:/data

networks:
  default:
    name: sso-demo_default
