services:
  backend:
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile.remote
      target: local
    container_name: sso-demo_backend
    ports:
      - "8012:8080"
      - "2345:2345"
    tty: true
    env_file:
      - "./backend/.env"
    # docker compose up --watch
    develop:
      watch:
        - action: rebuild
          path: ./backend
    # volumes:
    #   - ./backend:/go/src/backend

  redis:
    image: redis:latest
    container_name: sso-demo_redis
    ports:
      - "16379:6379"
    tty: true
    volumes:
      - ./redis/data:/data

networks:
  default:
    name: sso-demo_default
