name: Application and Infrastructure Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - dev
          - tst
      is_application_deploy:
        description: "Whether to deploy the application"
        required: true
        type: boolean
        default: true

jobs:
  push:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22.8

      - name: Setup dependencies
        run: npm ci

      - name: CDK Deploy
        run: |
          npx cdk deploy --all --require-approval never --githubToken ${{ secrets.AMPLIFY_GITHUB_TOKEN }} --backendImageTag ${{ github.sha }}
