name: Deploy to Amazon ECS

"on":
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
      is_application_deploy:
        description: "Whether to deploy the application"
        required: true
        default: "true"

env:
  # Assume role to be used for deploying to AWS.
  ROLE_TO_ASSUME: ${{ vars.AWS_ROLE_TO_ASSUME }}

jobs:
  push:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22.8

      - name: Setup dependencies
        run: npm ci

      - name: CDK Deploy
        run: |
          npx cdk deploy --all --require-approval never --githubToken ${{ secrets.AMPLIFY_GITHUB_TOKEN }} --backendImageTag ${{ github.sha }}
